#!/usr/bin/env zsh

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

export ZSH_CUSTOM="$ZDOTDIR/custom"
export MANPATH="/usr/local/man:$MANPATH"

export LANG=en_US.UTF-8 
export LANGUAGE=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export VISUAL='vim'
  export EDITOR='vim'
else
  export VISUAL='nvim'
  export EDITOR='nvim'
fi

# chezetc env
export PATH="$PATH:$HOME/.chezetc"

# dotnet env
export PATH="$PATH:$HOME/.dotnet/tools"
# go env
export GOPATH="$HOME/.local/share/go"
# export GOBIN=$HOME/.local/share/go/bin
# cargo 
export PATH="$HOME/.cargo/bin:$PATH"
export PATH=$PATH:$GOPATH/bin
# electron mirror
export ELECTRON_MIRROR="https://npmmirror.com/mirrors/electron/"
#nvm
# source /usr/share/nvm/init-nvm.sh
# fvm and flutter
export FVM_FLUTTER_URL="https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git"
export FLUTTER_STORAGE_BASE_URL="https://mirrors.tuna.tsinghua.edu.cn/flutter"
export PATH="$PATH:$HOME/fvm/default/bin"
export PATH="$PATH":"$HOME/.pub-cache/bin"
# py env
# export PYENV_ROOT="$HOME/.pyenv"
# eval "$(pyenv init -)"
export LIBVIRT_DEFAULT_URI="qemu:///system"

export QML_IMPORT_PATH="/usr/lib/qt6/qml"
# gpg as ssh-agent
# export GPG_TTY=$(tty)
# export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
# echo UPDATESTARTUPTTY | gpg-connect-agent 1> /dev/null

# bitwarden as ssh-agent
# export SSH_AUTH_SOCK=$HOME/.bitwarden-ssh-agent.sock
# rbw as ssh-agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/rbw/ssh-agent-socket"

# Nvidia hardware acceleration
# export VDPAU_DRIVER=nvidia
