color0 #131313
color1 #ffb4ab
color2 #99cbff
color3 #b9c8da
color4 #d4bee6
color5 #99cbff
color6 #b9c8da
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #99cbff
color11 #b9c8da
color12 #d4bee6
color13 #99cbff
color14 #b9c8da
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #99cbff
inactive_border_color #474747
url_color             #99cbff

active_tab_foreground   #003354
active_tab_background   #99cbff
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
