enable_audio_bell no
font_size 19.0
cursor_trail 1
cursor_trail_decay 0.05 0.4

scrollback_lines 10000

# tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Uncomment the following 4 lines to minimize kitty latency (higher energy usage)
input_delay 1
repaint_delay 2
sync_to_monitor no
# wayland_enable_ime no

# color 
background_opacity 0.7
transparent_background_colors red@0.5 #00ff00@0.3 #1a1d23@0.9

window_margin_width 0
window_padding_width 0


allow_hyperlinks yes
shell_integration enabled
allow_remote_control yes
listen_on unix:/tmp/kitty
action_alias kitty_scrollback_nvim kitten /home/ycna/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --env NVIM_APPNAME=nvim  --nvim-args -n
map kitty_mod+h kitty_scrollback_nvim --config myconfig

include map.conf

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
#



# BEGIN_KITTY_FONTS
font_family      family="Maple Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
